N_TOKENS = VERTEX_VOCABULARY = 4
POSITIONS = N_TOKENS*(N_TOKENS-1)
N_TOKENS = N_TOKENS + 4

AVAILABLE_TOKEN = VERTEX_VOCABULARY
FORBIDDEN_TOKEN = VERTEX_VOCABULARY + 1
END_OBSERVATION_TOKEN = VERTEX_VOCABULARY + 2
PAD_TOKEN = VERTEX_VOCABULARY + 3